# SPDX-FileCopyrightText: Elias Mueller
#
# SPDX-License-Identifier: MIT

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
