# SPDX-FileCopyrightText: Elias Mueller
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "go.sum"
precedence = "aggregate"
SPDX-FileCopyrightText = "Elias Mueller"
SPDX-License-Identifier = "MIT"
