# SPDX-FileCopyrightText: Elias Mueller
#
# SPDX-License-Identifier: MIT

name: CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.24']

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  release:
    name: Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -o qmlimportsort .
          zip qmlimportsort-${{ steps.version.outputs.VERSION }}-linux-amd64.zip qmlimportsort
          rm qmlimportsort

      - name: Build Linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build -o qmlimportsort .
          zip qmlimportsort-${{ steps.version.outputs.VERSION }}-linux-arm64.zip qmlimportsort
          rm qmlimportsort

      - name: Build macOS AMD64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o qmlimportsort .
          zip qmlimportsort-${{ steps.version.outputs.VERSION }}-darwin-amd64.zip qmlimportsort
          rm qmlimportsort

      - name: Build macOS ARM64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o qmlimportsort .
          zip qmlimportsort-${{ steps.version.outputs.VERSION }}-darwin-arm64.zip qmlimportsort
          rm qmlimportsort

      - name: Build Windows AMD64
        run: |
          GOOS=windows GOARCH=amd64 go build -o qmlimportsort.exe .
          zip qmlimportsort-${{ steps.version.outputs.VERSION }}-windows-amd64.zip qmlimportsort.exe
          rm qmlimportsort.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            qmlimportsort-${{ steps.version.outputs.VERSION }}-linux-amd64.zip
            qmlimportsort-${{ steps.version.outputs.VERSION }}-linux-arm64.zip
            qmlimportsort-${{ steps.version.outputs.VERSION }}-darwin-amd64.zip
            qmlimportsort-${{ steps.version.outputs.VERSION }}-darwin-arm64.zip
            qmlimportsort-${{ steps.version.outputs.VERSION }}-windows-amd64.zip
          draft: true
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
